name: Build & Test

on:
  push:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      QC_TASTYTRADE_USERNAME: ${{ secrets.QC_TASTYTRADE_USERNAME }}
      QC_TASTYTRADE_PASSWORD: ${{ secrets.QC_TASTYTRADE_PASSWORD }}
      QC_TASTYTRADE_ACCOUNT_NUMBER: ${{ secrets.QC_TASTYTRADE_ACCOUNT_NUMBER }}
      QC_TASTYTRADE_API_URL: ${{ secrets.QC_TASTYTRADE_API_URL }}
      QC_TASTYTRADE_WEBSOCKET_URL: ${{ secrets.QC_TASTYTRADE_WEBSOCKET_URL }}
      QC_JOB_USER_ID: ${{ secrets.QC_JOB_USER_ID }}
      QC_API_ACCESS_TOKEN: ${{ secrets.QC_API_ACCESS_TOKEN }}
      QC_JOB_ORGANIZATION_ID: ${{ secrets.QC_JOB_ORGANIZATION_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Liberate disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          large-packages: false
          docker-images: false
          swap-storage: false
      - name: Checkout Lean Same Branch
        id: lean-same-branch
        uses: actions/checkout@v2
        continue-on-error: true
        with:
          ref: ${{ github.ref }}
          repository: QuantConnect/Lean
          path: Lean

      - name: Checkout Lean Master
        if: steps.lean-same-branch.outcome != 'success'
        uses: actions/checkout@v2
        with:
          repository: QuantConnect/Lean
          path: Lean

      - name: Move Lean
        run: mv Lean ../Lean

      - uses: addnab/docker-run-action@v3
        with:
          image: quantconnect/lean:foundation
          options: --workdir /__w/Lean.Brokerages.Tastytrade/Lean.Brokerages.Tastytrade -v /home/runner/work:/__w -e QC_TASTYTRADE_USERNAME=${{ secrets.QC_TASTYTRADE_USERNAME }} -e QC_TASTYTRADE_PASSWORD=${{ secrets.QC_TASTYTRADE_PASSWORD }} -e QC_TASTYTRADE_API_URL=${{ secrets.QC_TASTYTRADE_API_URL }} -e QC_TASTYTRADE_WEBSOCKET_URL=${{ secrets.QC_TASTYTRADE_WEBSOCKET_URL }} -e QC_TASTYTRADE_ACCOUNT_NUMBER=${{ secrets.QC_TASTYTRADE_ACCOUNT_NUMBER }} -e QC_JOB_USER_ID=${{ secrets.QC_JOB_USER_ID }} -e QC_API_ACCESS_TOKEN=${{ secrets.QC_API_ACCESS_TOKEN }} -e QC_JOB_ORGANIZATION_ID=${{ secrets.QC_JOB_ORGANIZATION_ID }}
          shell: bash
          run: |
            # Build
            dotnet build /p:Configuration=Release /v:quiet /p:WarningLevel=1 QuantConnect.Tastytrade.sln && \
            # Run Tests
            dotnet test ./QuantConnect.TastytradeBrokerage.Tests/bin/Release/QuantConnect.Brokerages.Tastytrade.Tests.dll
